"""Collect/service independent host requests; never generates model responses.

The operating language model reads `next` output and writes the response records.
No completion endpoint or agent invocation is hidden in this convenience script.
"""
import argparse
import hashlib
import json
from pathlib import Path
from neuroevolution_lab.config import ExperimentSpec
from neuroevolution_lab.runtime import execute,resume_run,atomic_json,encoded
from neuroevolution_lab.providers import next_request,submit_response
from neuroevolution_lab.cli import heldout

def prepare(root,methods,seeds):
    if root.exists(): raise ValueError("Choose a new output directory")
    root.mkdir(parents=True)
    specs=[]
    for method in methods:
        for seed in seeds:
            spec=ExperimentSpec(name=f"{method}-seed{seed}",method=method,target="arithmetic_tools",seed=seed,
                population_size=2,generations=2,parameters={"train_cases":2},
                model={"provider":"bridge","model":"operating-agent","max_output_tokens":1024},
                budget={"max_evaluations":4,"max_model_calls":8,"wall_seconds":600})
            specs.append(spec.model_dump())
    protocol={"specifications":specs,"training_cases":"cases(seed+71, 2)","heldout_seed":"10000+seed","heldout_cases":8,
              "metric":"exact heldout success fraction; five independent task/experiment seeds, host decoding RNG uncontrolled",
              "comparators":"fixed_agent, random_agent, greedy_agent when present; candidate budgets equal; model requests differ",
              "model_evidence":"Every response must be generated by the operating language model reading the actual request, not a response-synthesis program",
              "freeze_sha256":hashlib.sha256(encoded(specs).encode()).hexdigest()}
    atomic_json(root/"protocol.json",protocol)
    for s in specs: execute(ExperimentSpec.model_validate(s),root/s["name"])

def advance(root):
    protocol=json.loads((root/"protocol.json").read_text())
    for spec in protocol["specifications"]:
        path=root/spec["name"]
        status=json.loads((path/"status.json").read_text())
        if status["status"]=="waiting_for_model" and next_request(path) is None: status=resume_run(path)
        hpath=root/(spec["name"]+"-heldout")
        if status["status"]=="completed" and not hpath.exists():
            heldout(path,hpath,seed=10000+spec["seed"],count=8)
        if hpath.exists():
            hs=json.loads((hpath/"status.json").read_text())
            if hs["status"]=="waiting_for_model" and next_request(hpath) is None: resume_run(hpath)

def pending(root):
    advance(root)
    result=[]
    for path in sorted(root.iterdir()):
        if path.is_dir() and (path/"status.json").exists():
            r=next_request(path)
            if r: result.append({"run":path.name,**r})
    return result

def main():
    parser=argparse.ArgumentParser(); parser.add_argument("command",choices=["prepare","next","submit","status"]); parser.add_argument("root",type=Path)
    parser.add_argument("--methods",nargs="+",default=["llm_workflow"]); parser.add_argument("--seeds",nargs="+",type=int,default=list(range(5)))
    parser.add_argument("--responses",type=Path); parser.add_argument("--provenance")
    args=parser.parse_args(); root=args.root.resolve()
    if args.command=="prepare": prepare(root,args.methods,args.seeds)
    elif args.command=="submit":
        if not args.provenance: parser.error("truthful --provenance is required")
        for r in json.loads(args.responses.read_text()):
            path=(root/r["run"]).resolve()
            if path.parent!=root: raise ValueError("Run must be directly inside batch root")
            submit_response(path,r["id"],r["text"],args.provenance)
        advance(root)
    if args.command=="status":
        print(encoded([{ "run":p.name,**json.loads((p/"status.json").read_text())} for p in sorted(root.iterdir()) if (p/"status.json").exists()]))
    else: print(encoded(pending(root)))

if __name__=="__main__": main()
