"""Independent scalar-NEAT comparisons and real journaled torch evaluations."""
import copy
import pickle
import random

import neat
import numpy as np
import pytest
import torch

from neuroevolution_lab.accelerator_structural import (
    ACTIVATIONS, AGGREGATIONS, SUPPORTED_ACTIVATIONS, SUPPORTED_AGGREGATIONS,
    TorchFeedForwardBatch, activate, aggregate, decode_cppn_batch,
    evaluate_structural_batch,
)
from neuroevolution_lab.structural import (
    CanonicalReproduction, StructuralEngine, ModularNASEngine, decode_cppn,
    train_architecture,
)
from neuroevolution_lab.devices import resolve_device


DEVICES = ["cpu", pytest.param("mps", marks=pytest.mark.skipif(
    not torch.backends.mps.is_available(), reason="MPS unavailable")),
    pytest.param("cuda", marks=pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA unavailable"))]


def mixed_genomes(method="neat", target="xor"):
    """Manually varied DAGs, not graphs generated by the tensor compiler."""
    engine = StructuralEngine({"method": method, "target": target, "seed": 31,
                               "population_size": 4, "generations": 2})
    base = next(iter(engine.population.population.values()))
    genomes = []
    for index, activation in enumerate(sorted(SUPPORTED_ACTIVATIONS)):
        genome = copy.deepcopy(base); genome.key = index
        for node in genome.nodes.values():
            node.activation = activation
            node.aggregation = sorted(SUPPORTED_AGGREGATIONS)[index % 7]
            node.bias = .2; node.response = .7
        for number, connection in enumerate(genome.connections.values()):
            connection.weight = (number % 3-1)*.13
            if index % 3 == 0 and number % 2 == 0: connection.enabled = False
            if index == 0: connection.enabled = False  # orphan output still expresses its bias
        if index % 3 != 0:
            node = copy.deepcopy(genome.nodes[0]); node.key = 100
            node.activation = "tanh"; node.aggregation = "sum"
            genome.nodes[node.key] = node
            for number, edge in enumerate([(-1, 100), (100, 0)]):
                connection = neat.genes.DefaultConnectionGene(edge, innovation=1000+number)
                connection.weight = .4; connection.enabled = True
                if index == 5 and edge == (-1, 100): connection.enabled = False
                genome.connections[edge] = connection
        if index % 3 == 2:
            node = copy.deepcopy(genome.nodes[100]); node.key = 101; node.activation = "sin"
            genome.nodes[node.key] = node
            for number, edge in enumerate([(100, 101), (101, 0)]):
                connection = neat.genes.DefaultConnectionGene(edge, innovation=1002+number)
                connection.weight = -.2; connection.enabled = True
                genome.connections[edge] = connection
        genomes.append(genome)
    return engine, genomes


@pytest.mark.parametrize("device", DEVICES)
def test_all_builtin_activations_match_independent_neat_scalar(device):
    dtype = torch.float64 if device == "cpu" else torch.float32
    points = [-100., -3.4, -1., -.01, 0., .01, 1., 3.4, 100.]
    inputs = torch.tensor(points, device=device, dtype=dtype)
    assert set(neat.activations.ActivationFunctionSet().functions) == SUPPORTED_ACTIVATIONS
    for name in SUPPORTED_ACTIVATIONS:
        expected = [ACTIVATIONS[name](x) for x in points]
        actual = activate(name, inputs).cpu().numpy()
        np.testing.assert_allclose(actual, expected, rtol=2e-6 if device != "cpu" else 1e-13, atol=2e-7)


@pytest.mark.parametrize("device", DEVICES)
def test_all_aggregations_padding_empty_even_median_and_maxabs_ties(device):
    dtype = torch.float64 if device == "cpu" else torch.float32
    rows = [[-2., 2.], [3., -4., 1.], [], [.3], [6., -1., 3., 2.]]
    values = torch.tensor([row+[999.]*(4-len(row)) for row in rows], dtype=dtype, device=device)[:, None, :]
    mask = torch.tensor([[True]*len(row)+[False]*(4-len(row)) for row in rows], device=device)
    assert set(neat.aggregations.AggregationFunctionSet().functions) == SUPPORTED_AGGREGATIONS
    for name in SUPPORTED_AGGREGATIONS:
        actual = aggregate(name, values, mask)[:, 0].cpu().numpy()
        np.testing.assert_allclose(actual, [AGGREGATIONS[name](row) for row in rows], rtol=2e-6, atol=1e-7)


@pytest.mark.parametrize("device", DEVICES)
def test_heterogeneous_topologies_activations_aggregations_match_scalar_network(device):
    engine, genomes = mixed_genomes(target="navigation")
    batch = TorchFeedForwardBatch(genomes, engine.config, device=device)
    inputs = np.random.default_rng(12).uniform(-.8, .8, (len(genomes), 7, 4))
    expected = [[neat.nn.FeedForwardNetwork.create(genome, engine.config).activate(row.tolist())
                 for row in observations] for genome, observations in zip(genomes, inputs)]
    actual = batch(inputs).cpu().numpy()
    np.testing.assert_allclose(actual, expected, rtol=2e-5 if device != "cpu" else 1e-12, atol=2e-6)
    # No cross-call residual state, including nodes with no expressed incoming links.
    np.testing.assert_array_equal(batch(inputs).cpu().numpy(), actual)


def test_reject_custom_or_overridden_functions_and_recurrent_phenotypes():
    engine, genomes = mixed_genomes()
    engine.config.genome_config.feed_forward = False
    with pytest.raises(ValueError, match="feed-forward"):
        TorchFeedForwardBatch(genomes, engine.config)
    engine.config.genome_config.feed_forward = True
    config = copy.deepcopy(engine.config)
    config.genome_config.activation_defs.add(genomes[1].nodes[0].activation, lambda z: z+1)
    with pytest.raises(ValueError, match="activation"):
        TorchFeedForwardBatch([genomes[1]], config)
    config = copy.deepcopy(engine.config)
    config.genome_config.aggregation_function_defs.add(genomes[1].nodes[0].aggregation, lambda xs: 0.)
    with pytest.raises(ValueError, match="aggregation"):
        TorchFeedForwardBatch([genomes[1]], config)
    with pytest.raises(ValueError, match="Expected observations"):
        TorchFeedForwardBatch(genomes, engine.config)([[1., 2.]])


@pytest.mark.parametrize("device", DEVICES)
def test_hyperneat_weights_match_independent_scalar_coordinate_decoder(device):
    engine, genomes = mixed_genomes("hyperneat", "navigation")
    # Bounded CPPN choices include different encodings and expression boundaries.
    networks = TorchFeedForwardBatch(genomes, engine.config, device=device)
    actual = decode_cppn_batch(networks, 4, 3, 2, threshold=.17, weight_scale=2.7).cpu().numpy()
    expected = [decode_cppn(neat.nn.FeedForwardNetwork.create(genome, engine.config),
                            4, 3, 2, threshold=.17, weight_scale=2.7) for genome in genomes]
    np.testing.assert_allclose(actual, expected, rtol=3e-5 if device != "cpu" else 1e-12, atol=3e-6)
    assert (actual > 0).any() and (actual < 0).any() and (actual == 0).any()


@pytest.mark.parametrize("method,target", [("neat", "xor"), ("neat", "cartpole"),
    ("neat", "navigation"), ("cppn", "pattern"), ("hyperneat", "xor"), ("hyperneat", "navigation")])
def test_real_batched_fitness_matches_reference(method, target):
    engine = StructuralEngine({"method": method, "target": target, "seed": 19,
        "population_size": 4, "generations": 1, "parameters": {"horizon": 25, "episodes": 2, "resolution": 7}})
    genomes = list(engine.population.population.values())
    actual = evaluate_structural_batch(genomes, engine.config, method, target, engine.seed, engine.parameters)
    expected = [engine._evaluate(genome, engine.seed) for genome in genomes]
    for measured, scalar in zip(actual, expected):
        assert measured["fitness"] == pytest.approx(scalar["fitness"], abs=1e-12)
        np.testing.assert_allclose(measured["descriptor"], scalar["descriptor"], atol=1e-12)
        for key in ["pixels", "decoded_weights", "trajectory", "predictions", "returns"]:
            if key in scalar["metrics"]:
                np.testing.assert_allclose(measured["metrics"][key], scalar["metrics"][key], atol=1e-12)


class BatchContext:
    def __init__(self):
        self.evaluations = []; self.events = []; self.batch_sizes = []; self.dispatched = False
    def evaluate_batch(self, genomes, fn, labels=None):
        self.dispatched = True
        results = fn(list(range(len(genomes))))
        self.dispatched = False
        self.evaluations.extend(results); self.batch_sizes.append(len(genomes))
        return results
    def evaluate(self, genome, fn, label=""):
        self.dispatched = True; result = fn(); self.dispatched = False
        self.evaluations.append(result); return result
    def record(self, event): self.events.append(event)


@pytest.mark.parametrize("device", DEVICES)
@pytest.mark.parametrize("method,target", [("neat", "cartpole"), ("cppn", "pattern"), ("hyperneat", "navigation")])
def test_real_torch_evolution_pickle_continuation_and_saved_controller_replay(device, method, target, monkeypatch):
    import neuroevolution_lab.accelerator_structural as accelerator
    engine = StructuralEngine({"method": method, "target": target, "seed": 4, "population_size": 5,
        "generations": 2, "parameters": {"horizon": 12, "episodes": 2, "resolution": 5},
        "compute": {"backend": "torch", "device": device, "batch_size": 3}})
    ambient = random.getstate(); context = BatchContext()
    evaluate = accelerator.evaluate_structural_batch
    def dispatched_only(*args, **kwargs):
        assert context.dispatched, "fitness work ran before context dispatch"
        return evaluate(*args, **kwargs)
    monkeypatch.setattr(accelerator, "evaluate_structural_batch", dispatched_only)
    engine.step(context)
    assert context.batch_sizes == [3, 2]
    assert type(engine.population.reproduction) is CanonicalReproduction
    resumed = pickle.loads(pickle.dumps(engine))
    engine.step(context); resumed.step(context)
    assert engine.summary() == resumed.summary()
    assert random.getstate() == ambient
    monkeypatch.setattr(accelerator, "evaluate_structural_batch", evaluate)
    replay = engine.replay()
    assert replay["fitness"] == pytest.approx(engine.best_result["fitness"], abs=1e-6)
    assert replay["metrics"]["device"] == str(resolve_device({"device": device}))
    np.testing.assert_allclose(replay["descriptor"], engine.best_result["descriptor"], atol=1e-6)
    assert np.isfinite(engine.replay(seed=5000)["fitness"])
    assert engine.summary()["evolution_backend"] == "canonical_neat_python"


def test_old_reference_checkpoint_without_compute_remains_reference():
    engine = StructuralEngine({"method": "neat", "population_size": 3, "generations": 1})
    engine.step(BatchContext()); del engine.compute
    restored = pickle.loads(pickle.dumps(engine))
    assert restored.replay() == restored.best_result
    assert restored.summary()["compute"]["backend"] == "reference"


def test_partial_cached_generation_dispatches_only_missing_genotypes(tmp_path, monkeypatch):
    import neuroevolution_lab.accelerator_structural as accelerator
    from neuroevolution_lab.runtime import Context, BudgetExceeded, encoded
    from neuroevolution_lab.config import ExperimentSpec
    spec = ExperimentSpec(method="neat", target="xor", population_size=5, generations=1,
        budget={"max_evaluations": 2}, compute={"backend": "torch", "batch_size": 3})
    start = StructuralEngine(spec.model_dump()); interrupted = copy.deepcopy(start)
    context = Context(tmp_path, spec)
    with pytest.raises(BudgetExceeded): interrupted.step(context)
    assert context.eval_count == 2
    spec.budget.max_evaluations = 5
    context = Context(tmp_path, spec)
    calls = []; original = accelerator.evaluate_structural_batch
    def counted(genomes, *args, **kwargs):
        calls.append([genome.key for genome in genomes]); return original(genomes, *args, **kwargs)
    monkeypatch.setattr(accelerator, "evaluate_structural_batch", counted)
    start.step(context)
    assert list(map(len, calls)) == [1, 2]
    fresh = StructuralEngine(spec.model_dump()); fresh.step(BatchContext())
    # Journal adds measurement_kind and default objectives, independent of batching.
    assert start.best_fitness == fresh.best_fitness
    assert encoded(start.summary()["best_genome"]) == encoded(fresh.summary()["best_genome"])
    assert context.eval_count == 5


@pytest.mark.parametrize("device", DEVICES)
def test_device_aware_nas_trains_then_replays_saved_weights_without_training(device, monkeypatch):
    import neuroevolution_lab.structural as structural
    settings = {"backend": "torch", "device": device, "batch_size": 3}
    architecture = {"widths": [4], "activations": ["tanh"]}
    ambient = torch.random.get_rng_state().clone()
    result = train_architecture(architecture, 15, steps=3, compute=settings)
    assert torch.equal(torch.random.get_rng_state(), ambient)
    assert result["metrics"]["device"] == str(resolve_device({"device": device}))
    assert result["metrics"]["evaluation_mode"] == "sequential_architectures"
    assert result["metrics"]["final_training_loss"] < result["metrics"]["initial_training_loss"]
    engine = ModularNASEngine({"method": "modular_nas", "seed": 15, "population_size": 2,
                               "generations": 1, "learning": {"steps": 2}, "compute": settings})
    engine.step(BatchContext()); engine = pickle.loads(pickle.dumps(engine))
    def forbidden(*args, **kwargs): raise AssertionError("replay retrained saved model")
    monkeypatch.setattr(structural, "train_architecture", forbidden)
    replay = engine.replay()
    assert replay["fitness"] == engine.best_result["fitness"]
    unseen = engine.replay(seed=200)
    assert unseen["metrics"]["trained_state"] == engine.best_result["metrics"]["trained_state"]
    assert unseen["metrics"]["device"] == str(resolve_device({"device": device}))


def test_reference_cannot_silently_run_on_accelerator():
    with pytest.raises(ValueError, match="reference structural backend"):
        StructuralEngine({"method": "neat", "compute": {"device": "mps", "backend": "reference"}})
